### ISSUE TITLE
Unexpected {/foreach}, expected {/=}

### ISSUE THREAD

**Issue by mitsh** [nette-intellij/intellij-latte#189]
**Describe the bug**
the plugin show an error for every last latte tag.

**Environment (please complete the following information):**
 - Intellij Build #IU-213.5744.223, built on November 27, 2021
 - Plugin version 1.1.4

**To Reproduce**
Steps to reproduce the behavior (or attach video):
![image](https://user-images.githubusercontent.com/895798/147078538-fd7aa648-2694-4ed4-aac0-41ceea36a46b.png)

**Code**
```latte
{if !empty($items)}
<h1 class="title-section">{$title ?? 'default-title'}</h1>
<div class="row section">
    {foreach $items as $item}
    {module('item', item:$item)}
    {/foreach}
</div>
{/if}

<div>test_integer: <input type="text" n:bind="$test_integer"/> <span n:bind="$test_integer">_{$test_integer}_</span></div>
<div>test_float: <input type="text" n:bind="$test_float"/> <span n:bind="$test_float">_{$test_float}_</span></div>
<div>test_string: <input type="text" n:bind="$test_string"/> <span n:bind="$test_string">_{$test_string}_</span></div>
<div>test_array: <input type="text" n:bind="$test_array"/> <span n:bind="$test_array">_{join(',', $test_array)}_</span></div>

```

**Comment by mesour** [comment]
@mitsh Try use next. Maybe it can be used as workaround.

```
{= module('item', item:$item)}
```

And then I think of: Don't you have a custom tag settings somewhere `=` and isn't it pair?

**Comment by mesour** [comment]
Fixed in v1.1.5

**Comment by xpavp03** [comment]
This error is still occurring for PhpStorm 2022.2 Windows, Plugin version 1.1.5
Not on Ubuntu version though.

```
{* This is the welcome page, you can delete it *}

{varType array $users}

{block content}

<h1>Ahoj</h1>

<table>
    {foreach $users as $item}
    <tr>
        <td>{$item->uzi_pk_id}</td>
        <td>{$item->uzi_jmeno . ' ' . $item->uzi_prijmeni}</td>
    </tr>
    {/foreach}
</table>

{/block}
```

**Comment by mesour** [comment]
@xpavp03 try Pro plugin: https://plugins.jetbrains.com/plugin/19661-latte-pro, here is migration guide from free plugin: https://mesour-intellij-plugins.github.io/latte.html#migration

Free plugin has a problem because it loads tags from XML and this is not possible in the parser (It is not possible for the parsing of one file to depend on the parsing of another, PhpStorm has async parsing.). I tried to fix it and it just caused the problem you describe. In the Pro plugin, it's all handled differently. I don't have time now, but in the future I will fix it in the Free plugin by removing the XML configuration. XML configuration will be only in Pro plugin.
